/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.ui;

/**
 * Main menu containing three primary buttons: Play, Match history, Exit.
 * @author Gabriel
 */
public class MainMenu extends javax.swing.JPanel {
    
    private GameWindow gameWindow;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu(GameWindow gameWindow) {
        initComponents();
        
        this.gameWindow = gameWindow;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        matchesButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridLayout(3, 1));

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/play.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        add(playButton);

        matchesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/replay.png"))); // NOI18N
        matchesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchesButtonActionPerformed(evt);
            }
        });
        add(matchesButton);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/exit.png"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // Hide this panel, and show the player names introduction's panel.
        gameWindow.remove(this);
        PlayerNamesIntroduction playerNames = new PlayerNamesIntroduction(gameWindow);
        
        gameWindow.add(playerNames);
        gameWindow.pack();
    }//GEN-LAST:event_playButtonActionPerformed

    private void matchesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchesButtonActionPerformed
        // Hide this panel, and show the matches list's panel.
        gameWindow.remove(this);
        MatchesList matchesList = new MatchesList(gameWindow);
        
        gameWindow.add(matchesList);
        gameWindow.pack();
    }//GEN-LAST:event_matchesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton matchesButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
