/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.ui;

import chess.Main;
import java.util.ArrayList;
import chess.gameplay.MatchResult;
import javax.swing.Box;

/**
 * Panel which provides visual support to show instances of MatchResultPanel.
 * @author Gabriel
 */
public class MatchesList extends javax.swing.JPanel {

    private GameWindow gameWindow;
    private Box box;
    /**
     * Creates new form MatchesList
     */
    public MatchesList(GameWindow gameWindow) {
        initComponents();
        
        this.gameWindow = gameWindow;
        
        // Create a vertical box in order to show the MatchResultPanel instances
        // vertically.
        box = Box.createVerticalBox();
        
        addMatches();
        invalidate();
    }
    
    /**
     * Create an instance of MatchResultPanel for each result held within
     * the database, and later they are added.
     */
    public void addMatches() {
        ArrayList<MatchResult> results = Main.getMatchWrapper().getResults();
        
        for (MatchResult result : results) {
            MatchResultPanel resultPanel = new MatchResultPanel(result);
            
            box.add(resultPanel);
        }
        
        scrollableList.setViewportView(box);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollableList = new javax.swing.JScrollPane();
        back = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.BorderLayout());

        scrollableList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollableList.setMaximumSize(new java.awt.Dimension(638, 478));
        scrollableList.setMinimumSize(new java.awt.Dimension(638, 478));
        scrollableList.setPreferredSize(new java.awt.Dimension(638, 478));
        scrollableList.setViewportView(null);
        add(scrollableList, java.awt.BorderLayout.CENTER);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // Hide this panel, and show the main menu.
        gameWindow.remove(this);
        MainMenu panel = new MainMenu(gameWindow);
        
        gameWindow.add(panel);
        gameWindow.pack();
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane scrollableList;
    // End of variables declaration//GEN-END:variables
}
