/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.ui;

import chess.gameplay.MatchResult;
import java.awt.Color;
import java.text.DateFormat;

/**
 * Panel which offers visual information about a previous match result.
 * @author Gabriel
 */
public class MatchResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form MatchResultPanel
     */
    public MatchResultPanel(MatchResult matchResult) {
        initComponents();
        
        String resultImage = "";
        
        switch (matchResult.getResultType()) {
            case MatchResult.DRAW:
                resultImage = "draw.png";
                setBackground(new Color(116, 116, 116));
                break;
            case MatchResult.PLAYER_1_VICTORY:
                resultImage = "player_1.png";
                setBackground(new Color(169, 187, 217));
                break;
            case MatchResult.PLAYER_2_VICTORY:
                resultImage = "player_2.png";
                setBackground(new Color(192, 217, 169));
                break;
            default:
                resultImage = "draw.png";
                setBackground(new Color(116, 116, 116));
                break;
        }
        
        DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM);
        
        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/" + resultImage)));
        versus.setText(String.format("%s vs %s", matchResult.getPlayer1Name(),
                matchResult.getPlayer2Name()));
        dateDetails.setText(String.format("Started at: %s; Finished at: %s",
                dateFormat.format(matchResult.getStartedAt()), 
                dateFormat.format(matchResult.getEndedAt())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result = new javax.swing.JLabel();
        versus = new javax.swing.JLabel();
        dateDetails = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 60));
        setMinimumSize(new java.awt.Dimension(400, 60));
        setPreferredSize(new java.awt.Dimension(400, 60));
        setLayout(new java.awt.BorderLayout());

        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/draw.png"))); // NOI18N
        add(result, java.awt.BorderLayout.LINE_START);

        versus.setText("Player 1 vs Player 2");
        add(versus, java.awt.BorderLayout.CENTER);

        dateDetails.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateDetails.setText("Started at: Finished at:");
        add(dateDetails, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateDetails;
    private javax.swing.JLabel result;
    private javax.swing.JLabel versus;
    // End of variables declaration//GEN-END:variables
}
